# Generated by Django 4.0.1 on 2022-04-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=5000)),
            ],
        ),
    ]
