# Generated by Django 4.0.1 on 2022-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='empmail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='empname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
