# Generated by Django 4.0.1 on 2022-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_empmail_jobs_empname'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
